import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
  
import { fetchEntries } from '../utils/contentfulMessage'
import Message from '../components/Message'

export default function Home({messages}) {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Schrijf het uit!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}> Schrijf het uit! </h1>

        <p className={styles.description}>
        De wereld staat op zijn kop. In deze geïsoleerde tijden was mentale gezondheid nog nooit zo belangrijk! 
        Toch wordt het steeds moeilijker om je gevoelens en frustraties te uitten. Zeker in de online wereld van vandaag.

        Daarom bied ik deze pagina aan in de hoop het iets gemakkelijker te maken deze gevoelens te verwerken.
        Schrijf hier uit wat op je hart ligt, maar je niet kan zeggen.
        </p>

        {/* hier komt het formulier */}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            
            <p>Wil je jouw boodschap toch met iemand delen? Klik dan hier</p>
            <h2>Delen &rarr;</h2>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            
            <p>Wil je je boodschap beveiligen? </p>
            <h2>Verbergen &rarr;</h2>
          </a>

        </div>

        {/* // inside your component markup, pull `messages` from props */}
        <div className="messages">
          {messages.map((message) => {
          
            return <Message key={message.url} mood={message.mood} message={message.message} title={message.title} />
          })}
        </div>
        <form name="test" data-netlify="true" method="POST">
          <p>
            <label>Message
              <textarea id="message" name="message"> </textarea>
            </label>
          </p>
          <button type="submit">Send</button>

        </form>
       
      </main>

      <footer className={styles.footer}>
         
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>

</>
  )
}
{/* // at the bottom of your component file */}

export async function getStaticProps() {
  const res = await fetchEntries()
  const messages = await res.map((p) => {
    return p.fields
  })

  return {
    props: {
      messages,
    },
  }
}